src/pages/index.tsx, src/pages/skills/[context]/[category]/add.tsx, src/pages/skills/[context]/[category]/index.tsx
=> ✨ Order skills

src/components/PageWithSkillList.tsx, src/components/Radar.tsx, src/components/SkillPanel.tsx, src/components/Topbar.tsx, src/pages/skills/[context]/[category]/index.tsx, tailwind.config.js
=> ✨ Replace sidebar with topmenu

hasura/metadata/tables.yaml, hasura/migrations/1619708682419_alter_table_public_Skill_alter_column_topicId/down.sql, hasura/migrations/1619708682419_alter_table_public_Skill_alter_column_topicId/up.sql, i18n/en.js, i18n/fr.js, src/components/AddSkilListSelector.tsx, src/pages/skills/[context]/[category]/add.tsx
=> ✨ Add skill functionality

i18n/en.js, i18n/fr.js, src/components/FilterByPanel.tsx, src/components/HomePanel.tsx, src/components/PageWithNavAndPanel.tsx, src/components/PageWithSkillList.tsx, src/pages/skills/[context]/[category]/index.tsx, src/pages/zenika.tsx, src/utils/types.ts, src/utils/useComputeFilterUrl.ts
=> [WIP] Filter by Agency

hasura/metadata/tables.yaml, hasura/migrations/1621458424098_run_sql_migration/up.sql, next.config.js, src/components/CommonPage.tsx, src/components/HomePanel.tsx, src/components/SkillPanel.tsx, src/components/Topbar.tsx, src/pages/profile/index.tsx, src/pages/skills/[context]/[category]/[skill]/index.tsx, src/pages/skills/[context]/[category]/add.tsx, src/pages/skills/[context]/[category]/index.tsx, src/pages/zenika.tsx
closes #60 #61 #72 and a problem with the agency fetched not being the latest
=> Fix various issues

package-lock.json, src/components/AddOrEditSkillModale.tsx
=> :zap: add automatic validating skills

.circleci/config.yml, src/pages/profile/[email]/index.tsx, src/pages/skills/[context]/[category]/add.tsx
=> fix search skill and view on unreachable page

src/pages/profile/[email]/index.tsx
=> Resolve bug profile achievement when we are searching a profile

src/graphql/queries/skills.ts
Closes https://github.com/Zenika/skillZ/issues/205
=> :children_crossing: List user's skills in alphabetical order

src/components/AddOrEditSkillModal.tsx
Closes https://github.com/Zenika/skillZ/issues/204
=> :children_crossing: changed validation behavior when updating skill

src/graphql/queries/skills.ts
It should fix the main staging bug. It was my bad, totally forgot this arg :-1:
=> :bug: change graph query to get only user email

src/components/CommonPage.tsx
Closes https://github.com/Zenika/skillZ/issues/203
=> :bug: Fix go back button

src/components/CommonPage.tsx, src/components/GraphQLProvider.tsx, src/components/HomePanel.tsx, src/components/SkillPanel.tsx, src/env.ts, src/pages/_app.tsx, src/pages/index.tsx, src/pages/logout.tsx
Refactor environment loading to avoid duplicate if statement 👍🏼
=> :technologist: refactor env loading

src/components/PageWithSkillList.tsx, src/components/SkillPanel.tsx
Closes https://github.com/Zenika/skillZ/issues/202
=> :children_crossing: user can now select a competency without clicking on it

src/components/SkillPanel.tsx
Closes https://github.com/Zenika/skillZ/issues/214
=> :bug: fix skill encode in URL

src/components/PageWithSkillList.tsx, src/graphql/queries/skills.ts, src/utils/fetchers/useFetchSkillsByContextCategoryAndAgency.tsx
Closes https://github.com/Zenika/skillZ/issues/198
=> :sparkles: add search bar in zenika agency skills list

src/components/AddOrEditSkillModal.tsx
Closes https://github.com/Zenika/skillZ/issues/226
=> :bug: fix wrong value for skill level in edit modal

src/components/SkillPanel.tsx
Closes https://github.com/Zenika/skillZ/issues/225
=> :children_crossing: swap skill level and desire in SkillPanel component

i18n/en.js, i18n/fr.js, src/styles/404.css
=> :pencil2: fix some traduction incoherencies

i18n/fr.js, src/components/AddSkilListSelector.tsx, src/graphql/mutations/skills.ts
Closes https://github.com/Zenika/skillZ/issues/178
=> :children_crossing: refactor AddSkillListSelector to avoid blinking while loading

i18n/en.js, i18n/fr.js, src/components/SkillPanel.tsx, src/graphql/queries/skills.ts, src/pages/search.tsx
=> :fire: delete useless request and add result number on search page

src/components/SearchBar.tsx
=> 🐛 💄 Fix default outline on search component

src/components/AddSkilListSelector.tsx
=> 🐛 💄 Fix skills cards styling

src/pages/profile/index.tsx
Closes https://github.com/Zenika/skillZ/issues/118
=> :fire: remove confirm button on profile page

i18n/en.js, i18n/fr.js, src/components/SidePanel.tsx, src/components/Topbar.tsx
Closes https://github.com/Zenika/skillZ/issues/245
Closes https://github.com/Zenika/skillZ/issues/234
Screenshots :
=> :lipstick: improve ui of menu dropdown

src/components/Radar.tsx
Closes https://github.com/Zenika/skillZ/issues/261
=> :lipstick: remove red lines on radar graph

src/components/profile/ViewAgency.tsx, src/pages/profile/index.tsx
=> :lipstick: delete margin and add padding in myProfile agency section

src/components/HomePanel.tsx, src/components/Radar.tsx, tailwind.config.js
Closes https://github.com/Zenika/skillZ/issues/281
=> :lipstick: fix colours on skills categories

src/components/profile/statistics/badges/BadgeSubojectivesCategoryCompletion.tsx, src/components/profile/statistics/progressBar/ProgressBar.module.css, src/components/profile/statistics/progressBar/ProgressBar.tsx
=> :poop: add comment and try to fix statistics

i18n/en.js, i18n/fr.js, src/components/AddSkilListSelector.tsx
resolve #257 
Easier like this
=> :hammer: add new condition to avoid to create dupplicate skillz

src/pages/_app.tsx
Closes https://github.com/Zenika/skillZ/issues/276
=> :bug: fix dark mode on loading page when components are not all mounted

cypress/e2e/profile.cy.ts, src/pages/profile/index.tsx
Closes https://github.com/Zenika/skillZ/issues/289
=> :bug: fix profile reloading issues

src/components/CustomSelect.tsx, src/components/profile/certifications/CertificationModal.tsx, src/pages/profile/index.tsx
Closes https://github.com/Zenika/skillZ/issues/290
=> :lipstick: fix margin issues

src/components/TopBar.tsx, src/graphql/queries/skills.ts, src/pages/admin.tsx
Closes https://github.com/Zenika/skillZ/issues/267
=> :sparkles: add admin notification badge

i18n/en.js, i18n/fr.js, src/components/NotificationPanel.tsx, src/graphql/queries/skills.ts, src/pages/admin.tsx, src/pages/profile/[email]/index.tsx
=> :sparkles: add search bar and all skils

i18n/en.js, i18n/fr.js, src/components/admin/EditSkillAdminModal.tsx, src/components/admin/SkillAdminPanel.tsx, src/graphql/mutations/skills.ts, src/graphql/queries/categories.ts, src/graphql/queries/skills.ts, src/pages/admin.tsx, src/utils/types.ts
Closes https://github.com/Zenika/skillZ/issues/287
=> :sparkles: Admin modal to edit skill

.circleci/config.yml
resolve #310 
The var env will take in account the Skillz core team + Pierre Brethes in dev and staging.
=> :green_heart: add new admins

src/components/SkillListOverview.tsx
Closes https://github.com/Zenika/skillZ/issues/66
=> :lipstick: improve ui of tab in SkillListOverview.tsx

src/components/CustomSelect.tsx, src/components/SkillTopics.tsx, src/components/admin/EditSkillAdminModal.tsx
Closes https://github.com/Zenika/skillZ/issues/313
=> :lipstick: improve CustomSelect.tsx component

src/components/AddOrEditSkillModal.tsx, src/components/SkillListOverview.tsx, tailwind.config.js
=> :lipstick: fixed modal scroll on mobile screen

src/components/CommonPage.tsx, src/components/profile/PreferedTopics.tsx, src/components/profile/ViewAgency.tsx, src/components/profile/certifications/CertificationsList.tsx, src/components/profile/statistics/Statistics.tsx, src/pages/profile/[email]/index.tsx, src/pages/profile/index.tsx, tailwind.config.js
=> :lipstick: fix light mode and refacto of common page component

src/pages/search.tsx
Closes https://github.com/Zenika/skillZ/issues/323
=> :sparkles: add back button on search

src/pages/index.tsx, src/pages/profile/[email]/graphs/index.tsx, src/pages/profile/[email]/index.tsx, src/pages/profile/index.tsx, src/pages/search.tsx, src/pages/skills/[context]/[category]/[skill]/index.tsx, src/pages/skills/[context]/[category]/index.tsx, src/pages/zenika.tsx
Closes https://github.com/Zenika/skillZ/issues/332
=> :bug: fix logout and account selection on login

i18n/en.js, i18n/fr.js
Closes https://github.com/Zenika/skillZ/issues/339
=> :globe_with_meridians: fix search page name

hasura/migrations/1668599500830_insert_into_public_Agency/down.sql, hasura/migrations/1668599500830_insert_into_public_Agency/up.sql, hasura/seeds/01-agencies.sql
=> :bug: delete agency lr migration

i18n/en.js, i18n/fr.js, src/components/LocaleSelector.tsx
=> :heavy_minus_sign: delete full switch color

.circleci/config.yml
=> :memo: update admin list

i18n/en.js, i18n/fr.js, src/components/admin/EditSkillAdmin.tsx, src/pages/admin.tsx
Closes https://github.com/Zenika/skillZ/issues/326
=> :fire: remove button on skill admin modal

README.md, package-lock.json, package.json
Closes https://github.com/Zenika/skillZ/issues/375
=> :technologist: add engines version requirements

hasura/metadata/tables.yaml, hasura/migrations/1668439064364_alter_table_public_UserSkillDesire_add_column_updated_at/down.sql, hasura/migrations/1668439064364_alter_table_public_UserSkillDesire_add_column_updated_at/up.sql, hasura/migrations/1668440387413_drop_view_public_UsersCurrentSkillsAndDesires/up.sql, hasura/migrations/1668440387420_run_update_users_current_skills_and_desires_view/up.sql, i18n/en.js, i18n/fr.js, src/components/AddOrEditSkill.tsx, src/components/SkillListOverview.tsx, src/graphql/mutations/skills.ts, src/graphql/queries/skills.ts, src/utils/fetchers/useFetchSkillsByContextCategoryAndAgency.tsx, src/utils/types.ts
Closes https://github.com/Zenika/skillZ/issues/318
Closes https://github.com/Zenika/skillZ/issues/357
=> :sparkles: add last updated date on each skill

src/components/Navbar.tsx, src/pages/admin.tsx
=> 🚧  admin tab in mobile bottom navbar

README.md, package-lock.json, package.json
I've upgrade my node to v16.13.0 and npm to 9.1.3
according to the last log of the staging : https://app.circleci.com/pipelines/github/Zenika/skillZ/1098/workflows/524302f7-2063-4cf4-b2a5-5dace0001381/jobs/5572/parallel-runs/0/steps/0-105
=> :arrow_up: upgrade npm version

src/pages/api/skills.ts
Requirement for https://github.com/Zenika/skillZ/issues/352
=> :sparkles: add endpoint to get all verified skills

i18n/en.js, i18n/fr.js, src/components/CustomSelect.tsx, src/components/TextArea.tsx, src/components/Topics.tsx, src/components/admin/EditSkillAdmin.tsx, src/components/admin/EditTags.tsx, src/components/admin/SkillAdminPanel.tsx, src/components/admin/SkillDescription.tsx, src/graphql/queries/skills.ts, src/pages/admin.tsx, src/utils/types.ts
=> :sparkles: open edit modal for unapproved skills

src/components/atoms/Topic.tsx, src/components/molecules/Topics.tsx
Closes https://github.com/Zenika/skillZ/issues/395
=> :bug: fix readonly in Topic.tsx and Topics.tsx component

src/components/atoms/CustomSelect/CustomSelect.tsx
=> :bug: fix custom select

.github/dependabot.yml
Closes https://github.com/Zenika/skillZ/issues/388
This PR adds configuration file for the dependabot PR :
- Create PRs every monday at 7:00 AM
- Labels "automated PR", "dependencies", "skillz-app" and "skillz-bot"
- Add @benjaminbrgs and @MailyLehoux as reviewers for the skillz-app
- Add @MailyLehoux as reviewer for the skillz-bot
=> :wrench: configuration file for dependabot

src/pages/api/skills.ts, src/utils/fetchers/getAllSkillsFetcher.tsx
This PR aims to fix the endpoint that will be used for the incoming PR that automate the update of the skills referential
=> :sparkles: add endpoint to get all skills

src/components/organisms/Profile.tsx
=> :bug: fix onboarding

.github/dependabot.yml, hasura/metadata/tables.yaml, hasura/migrations/1671544433085_alter_table_public_UserSkillDesire_drop_column_updated_at/down.sql, hasura/migrations/1671544433085_alter_table_public_UserSkillDesire_drop_column_updated_at/up.sql, hasura/migrations/1671632288861_create_view_currentSkillDesire/down.sql, hasura/migrations/1671632288861_create_view_currentSkillDesire/up.sql, src/components/organisms/AddOrEditSkill.tsx, src/components/organisms/SkillListOverview.tsx, src/graphql/mutations/skills.ts, src/graphql/queries/skills.ts, src/utils/fetchers/useFetchSkillsByContextCategoryAndAgency.tsx, src/utils/types.ts
=> :fire: replacing updated at with created at

hasura/local_seeds/seedscript.ts, next.config.js, package-lock.json, package.json
https://www.npmjs.com/package/faker is not maintained anymore.
Replaced with its successor
=> :arrow_up: update faker package to new package

docker-compose.yml, package-lock.json
Closes https://github.com/Zenika/skillZ/issues/474
=> :bug: fix hasura metadata

.circleci/config.yml, docker-compose.yml, hasura.Dockerfile
Closes https://github.com/Zenika/skillZ/issues/413
=> :arrow_up: upgrade hasura version from 2.8.4 to 2.16.1

README.md
=> :memo: add summary

README.md
Closes https://github.com/Zenika/skillZ/issues/494
=> :memo: update readme with Github Actions and Dependabot sections

src/components/organisms/HomePanel/HomePanel.tsx
Closes https://github.com/Zenika/skillZ/issues/406
=> :lipstick: fix graph title on homepage

src/components/organisms/charts/scatter/ScatterChart.tsx
Closes https://github.com/Zenika/skillZ/issues/502
=> 💄 Increase strokeWidth on ScatterChart

src/components/molecules/EditTags.tsx, src/components/organisms/SkillPanel.tsx
Closes https://github.com/Zenika/skillZ/issues/504
=> :bug: remove double action onClick on skilldetails

src/pages/api/agencies.ts, src/pages/api/certifications.ts, src/pages/api/tags.ts, src/pages/api/topics.ts, src/utils/fetchers/getAllAgenciesFetcher.tsx, src/utils/fetchers/getAllCertificationsFetcher.tsx, src/utils/fetchers/getAllTagsFetcher.tsx, src/utils/fetchers/getAllTopicsFetcher.tsx
Theses endpoints will be useful in the future to automatically update referential in the repository like this the skill referential
=> :rocket: add multiple endpoint to get data from Skillz

package-lock.json, src/components/organisms/HomePanel/HomePanel.tsx
Closes https://github.com/Zenika/skillZ/issues/533
=> :bug: fix graph display on firefox

src/components/atoms/AutoCompleteList.tsx, test/autocompletelist.test.tsx
Closes https://github.com/Zenika/skillZ/issues/531
=> :bug: fix dark line on AutoCompleteList

src/components/organisms/SkillListOverview.tsx
Closes https://github.com/Zenika/skillZ/issues/516
=> :bug: add placeholder in searchbar in SkillListOverview.tsx

package-lock.json, package.json
Closes https://github.com/Zenika/skillZ/issues/554
=> :package: add sharp package to optimize images in production

.github/dependabot.yml, README.md
Closes https://github.com/Zenika/skillZ/issues/556
=> :wrench: run dependabot monthly

package-lock.json, src/components/atoms/Tooltip.tsx, src/components/organisms/HomePanel/HomePanel.tsx
Closes https://github.com/Zenika/skillZ/issues/482
=> :sparkles: add tooltip component on category homepage

i18n/en.js, i18n/fr.js, package-lock.json, src/components/organisms/AddSkilListSelector.tsx, src/graphql/queries/skills.ts, src/pages/search.tsx
=> :sparkles: global search bar in category

src/components/atoms/AutoCompleteList.tsx
Closes https://github.com/Zenika/skillZ/issues/569
=> :bug: fix autocomplete position

hasura/metadata/tables.yaml, i18n/en.js, i18n/fr.js, package-lock.json, src/components/molecules/UserPanel.tsx, src/components/organisms/CertificationPanel.tsx, src/components/organisms/Profile.tsx, src/components/organisms/SkillPanel.tsx, src/graphql/queries/certifications.ts, src/graphql/queries/skills.ts, src/pages/certifications/[certification]/index.tsx, src/pages/search.tsx, src/utils/types.ts
Closes https://github.com/Zenika/skillZ/issues/534
=> :sparkles: add certification results in search page

package-lock.json, src/components/organisms/SidePanel.tsx, src/components/templates/CommonPage.tsx
Closes https://github.com/Zenika/skillZ/issues/575
=> :bug: fix sidebar on mobile

i18n/en.js, i18n/fr.js, src/components/molecules/SkillName.tsx, src/components/organisms/EditSkillAdmin.tsx, src/graphql/mutations/skills.ts
Closes https://github.com/Zenika/skillZ/issues/587
=> :sparkles: Admin now able to rename a skill

src/pages/_app.tsx
Closes https://github.com/Zenika/skillZ/issues/588
=> :bug: fix mobile margin bottom

src/providers/AuthProvider.tsx
Closes https://github.com/Zenika/skillZ/issues/571
=> :zap: improve authentication flow

hasura/migrations/1679662647608_alter_table_public_User_add_column_role/down.sql, hasura/migrations/1679662647608_alter_table_public_User_add_column_role/up.sql, src/pages/api/users.ts, src/utils/fetchers/getAllUsers.tsx
https://github.com/Zenika/skillZ/issues/600
=> :sparkles: add admin endpoint and roles

src/pages/search.tsx
Closes https://github.com/Zenika/skillZ/issues/601
=> :fire: remove placeholder in search bar on Search Page
